/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.
 
 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
 // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void resetHit(GButton source, GEvent event) { //_CODE_:resetButton:874222:
  setup();
} //_CODE_:resetButton:874222:

public void pauseHis(GButton source, GEvent event) { //_CODE_:button1:393250:
  if (pause) {
    pause = false;
  } else {
    pause = true;
  }
} //_CODE_:button1:393250:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI() {
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  resetButton = new GButton(this, 777, 93, 53, 30);
  resetButton.setText("Reset");
  resetButton.setTextBold();
  resetButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  resetButton.addEventHandler(this, "resetHit");
  button1 = new GButton(this, 764, 47, 80, 30);
  button1.setText("Pause");
  button1.addEventHandler(this, "pauseHis");
}

// Variable declarations 
// autogenerated do not edit
GButton resetButton; 
GButton button1; 
